trigger:
 branches:
   exclude:
     - main

pool: 1agpool

stages:
  - stage: "TerraformInit"
    displayName: "Terraform init"
    jobs:
      - job: "InitPlan"
        displayName: "Terraform Init & Plan"
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendAzureRmStorageAccountName: 'mystoragefortfstatefile'
            backendAzureRmContainerName: 'mycontainerfortfstate'
            backendAzureRmKey: 'project01-tfstate'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'

  - stage: "TerraformApply"
    displayName: "Terraform Apply Step"
    jobs:
    - job: "terraformapply"
      displayName: "Terraform Apply Step"
      steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'apply'

