trigger:
 branches:
   exclude:
     - main

pool: 1agpool

stages:
  - stage: "TerraformInit"
    displayName: "Terraform init"
    jobs:
      - job: "InitPlan"
        displayName: "Terraform Init & Plan"
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/project01_dev02'
            backendServiceArm: 'sc-dev-tf-infra'
            backendAzureRmResourceGroupName: 'rgterraformstatefile'
            backendAzureRmStorageAccountName: 'mystoragefortfstatefile'
            backendAzureRmContainerName: 'mycontainerfortfstate'
            backendAzureRmKey: 'project01-tfstate'
        

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/project01_dev02'
            environmentServiceNameAzureRM: 'sc-dev-tf-infra'

  - stage: "TerraformApply"
    displayName: "Terraform Apply Step"
    jobs:
    - job: "tfapply"
      displayName: "Terraform Apply Step"
      steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'apply'

